name: filebrowser

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.30
    volumes:
      - ./data/files:/srv
      - ./data/db:/database
      - ./data/config:/config

networks:
  localnet:
    external: true
