name: glance

services:
  glance:
    image: glanceapp/glance
    container_name: glance
    networks:
      localnet:
        ipv4_address: 172.20.0.30
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  localnet:
    external: true
